# -*- coding: utf-8 -*-
"""NumbaParallelization2D Heat Equation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkVg48GM_bQ9_LHFXuKYQzkdATHSznlq
"""

import numpy as np
from numba import njit, prange
import time
import os

# The parallel=True flag tells Numba to use its threading layer (often backed by OpenMP)
@njit(parallel=True)
def solve_heat_equation(u, u_next, alpha, dx, dy, dt, iterations):

    nx = u.shape[0]
    ny = u.shape[1]

    for step in range(iterations):

        # prange automatically distributes the outer loop across available CPU threads
        for i in prange(1, nx - 1):
            for j in range(1, ny - 1):
                u_next[i, j] = u[i, j] + alpha * dt * (
                    (u[i+1, j] - 2.0 * u[i, j] + u[i-1, j]) / (dx * dx) +
                    (u[i, j+1] - 2.0 * u[i, j] + u[i, j-1]) / (dy * dy)
                )

        # Copy the updated array back to u for the next iteration
        # We use prange here again to parallelize the memory copy
        for i in prange(1, nx - 1):
            for j in range(1, ny - 1):
                u[i, j] = u_next[i, j]


def main():

    # 1. Setup Grid Parameters (Large enough to make scaling visible)
    nx, ny = 2000, 2000
    iterations = 500
    alpha = 0.01
    dx, dy = 0.1, 0.1

    # CFL stability condition
    dt = (dx**2 * dy**2) / (2.0 * alpha * (dx**2 + dy**2))

    # 2. Initialize Arrays
    u = np.zeros((nx, ny), dtype=np.float64)
    u_next = np.zeros((nx, ny), dtype=np.float64)

    # Set simple boundary conditions
    u[0, :] = 100.0
    u[-1, :] = 0.0
    u[:, 0] = 50.0
    u[:, -1] = 50.0

    # 3. WARM-UP RUN (Crucial for Numba)
    # First call compiles function so compilation time isn't benchmarked
    solve_heat_equation(np.zeros((10,10)),
                        np.zeros((10,10)),
                        alpha, dx, dy, dt, 1)

    # 4. Benchmark
    start = time.time()

    solve_heat_equation(u, u_next, alpha, dx, dy, dt, iterations)

    end = time.time()

    print("Execution time:", end - start, "seconds")


if __name__ == "__main__":
    main()